/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import javax.swing.ImageIcon;

/**
 *
 * @author lubuntu
 */
public class Principal extends javax.swing.JFrame {
        int contMaquina = 0;
        int contJogador = 0;
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelMaquina = new javax.swing.JLabel();
        jLabelMAQUINA = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabelJogador = new javax.swing.JLabel();
        jLabelJOGADOR = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButtonSetarPedra = new javax.swing.JButton();
        jButtonSetarPapel = new javax.swing.JButton();
        jButtonSetarTesoura = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelPlacarMaquina = new javax.swing.JLabel();
        jLabelPlacarJogador = new javax.swing.JLabel();
        jButtonIniciar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButtonReiniciar = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.setPreferredSize(new java.awt.Dimension(450, 445));

        jLabelMaquina.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMaquina.setText("Pressione Iniciar...");

        jLabelMAQUINA.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabelMAQUINA.setText("Máquina");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabelMaquina, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelMAQUINA)
                .addGap(109, 109, 109))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelMAQUINA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelMaquina, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabelJogador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelJogador.setText("Pressione Iniciar...");

        jLabelJOGADOR.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabelJOGADOR.setText("Jogador");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(73, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelJogador, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelJOGADOR)
                        .addGap(111, 111, 111))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelJOGADOR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelJogador, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jButtonSetarPedra.setBackground(new java.awt.Color(204, 204, 204));
        jButtonSetarPedra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pedra.png"))); // NOI18N
        jButtonSetarPedra.setBorder(null);
        jButtonSetarPedra.setEnabled(false);
        jButtonSetarPedra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSetarPedraActionPerformed(evt);
            }
        });

        jButtonSetarPapel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/papel.png"))); // NOI18N
        jButtonSetarPapel.setBorder(null);
        jButtonSetarPapel.setEnabled(false);
        jButtonSetarPapel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSetarPapelActionPerformed(evt);
            }
        });

        jButtonSetarTesoura.setBackground(new java.awt.Color(204, 204, 204));
        jButtonSetarTesoura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/tesoura.png"))); // NOI18N
        jButtonSetarTesoura.setBorder(null);
        jButtonSetarTesoura.setEnabled(false);
        jButtonSetarTesoura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSetarTesouraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jButtonSetarPedra)
                .addGap(81, 81, 81)
                .addComponent(jButtonSetarPapel, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addComponent(jButtonSetarTesoura)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonSetarPedra, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSetarTesoura, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSetarPapel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setText("X");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("Placar");

        jLabelPlacarMaquina.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelPlacarMaquina.setText("0");

        jLabelPlacarJogador.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelPlacarJogador.setText("0");

        jButtonIniciar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonIniciar.setText("Iniciar");
        jButtonIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIniciarActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setText("x");

        jButtonReiniciar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonReiniciar.setText("Reiniciar");
        jButtonReiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReiniciarActionPerformed(evt);
            }
        });

        jButtonSair.setBackground(new java.awt.Color(255, 255, 255));
        jButtonSair.setText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButtonSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonReiniciar, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
            .addComponent(jButtonIniciar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(34, 34, 34))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabelPlacarMaquina)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelPlacarJogador))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabelPlacarJogador)
                    .addComponent(jLabelPlacarMaquina))
                .addGap(123, 123, 123)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(jButtonIniciar)
                .addGap(18, 18, 18)
                .addComponent(jButtonReiniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 920, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIniciarActionPerformed
        // TODO add your handling code here:
        ImageIcon imgvazio = new ImageIcon("./src/imagens/vazio.png");
        
        jLabelJogador.setIcon(imgvazio);
        jLabelMaquina.setIcon(imgvazio);
        
        jButtonSetarPedra.setEnabled(true);
        jButtonSetarPapel.setEnabled(true);
        jButtonSetarTesoura.setEnabled(true);
        
        jLabelMAQUINA.setForeground(Color.black);
        jLabelJOGADOR.setForeground(Color.black);
        
        jPanel3.setBackground(Color.WHITE);
    }//GEN-LAST:event_jButtonIniciarActionPerformed

    private void jButtonSetarPedraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSetarPedraActionPerformed
        ImageIcon imgtesoura = new ImageIcon("./src/imagens/tesoura.png");
        ImageIcon imgpapel = new ImageIcon("./src/imagens/papel.png");
        ImageIcon imgpedra = new ImageIcon("./src/imagens/pedra.png");
        jLabelJogador.setIcon(imgpedra);
        
        int randomnumber = (int) ( 1 + Math.random() * (4-1));
        
        if(randomnumber == 1){
            jLabelMaquina.setIcon(imgpedra);
            jLabelMAQUINA.setForeground(Color.black);
            jLabelJOGADOR.setForeground(Color.black);
        }
        if(randomnumber == 2){
            jLabelMaquina.setIcon(imgpapel);
            contMaquina++;
            jLabelMAQUINA.setForeground(Color.green);
            jLabelJOGADOR.setForeground(Color.red);
        }
        if(randomnumber == 3){
            jLabelMaquina.setIcon(imgtesoura);
            contJogador++;
            jLabelMAQUINA.setForeground(Color.red);
            jLabelJOGADOR.setForeground(Color.green);
        }
        
        
        
        jLabelPlacarMaquina.setText(Integer.toString(contMaquina));
        jLabelPlacarJogador.setText(Integer.toString(contJogador));
    }//GEN-LAST:event_jButtonSetarPedraActionPerformed

    private void jButtonSetarPapelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSetarPapelActionPerformed
        ImageIcon imgtesoura = new ImageIcon("./src/imagens/tesoura.png");
        ImageIcon imgpapel = new ImageIcon("./src/imagens/papel.png");
        ImageIcon imgpedra = new ImageIcon("./src/imagens/pedra.png");
        jLabelJogador.setIcon(imgpapel);
        
        int randomnumber = (int) ( 1 + Math.random() * (4-1));
        
        if(randomnumber == 1){
            jLabelMaquina.setIcon(imgpedra);
            contJogador++;
            jLabelMAQUINA.setForeground(Color.red);
            jLabelJOGADOR.setForeground(Color.green);
        }
        if(randomnumber == 2){
            jLabelMaquina.setIcon(imgpapel);
            jLabelMAQUINA.setForeground(Color.black);
            jLabelJOGADOR.setForeground(Color.black);
        }
        if(randomnumber == 3){
            jLabelMaquina.setIcon(imgtesoura);
            contMaquina++;
            jLabelMAQUINA.setForeground(Color.green);
            jLabelJOGADOR.setForeground(Color.red);
        }

        jLabelPlacarMaquina.setText(Integer.toString(contMaquina));
        jLabelPlacarJogador.setText(Integer.toString(contJogador));
    }//GEN-LAST:event_jButtonSetarPapelActionPerformed

    private void jButtonSetarTesouraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSetarTesouraActionPerformed
        ImageIcon imgtesoura = new ImageIcon("./src/imagens/tesoura.png");
        ImageIcon imgpapel = new ImageIcon("./src/imagens/papel.png");
        ImageIcon imgpedra = new ImageIcon("./src/imagens/pedra.png");
        jLabelJogador.setIcon(imgtesoura);
        
        int randomnumber = (int) ( 1 + Math.random() * (4-1));
        
        if(randomnumber == 1){
            jLabelMaquina.setIcon(imgpedra);
            contMaquina++;
            jLabelMAQUINA.setForeground(Color.green);
            jLabelJOGADOR.setForeground(Color.red);
        }
        if(randomnumber == 2){
            jLabelMaquina.setIcon(imgpapel);
            contJogador++;
            jLabelMAQUINA.setForeground(Color.red);
            jLabelJOGADOR.setForeground(Color.green);
        }
        if(randomnumber == 3){
            jLabelMaquina.setIcon(imgtesoura);
            jLabelMAQUINA.setForeground(Color.black);
            jLabelJOGADOR.setForeground(Color.black);
        }

        jLabelPlacarMaquina.setText(Integer.toString(contMaquina));
        jLabelPlacarJogador.setText(Integer.toString(contJogador));
    }//GEN-LAST:event_jButtonSetarTesouraActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReiniciarActionPerformed
        // TODO add your handling code here:
        contJogador = 0;
        contMaquina = 0;
        
        jLabelPlacarJogador.setText(Integer.toString(contJogador));
        jLabelPlacarMaquina.setText(Integer.toString(contMaquina));
        jLabelMAQUINA.setForeground(Color.black);
        jLabelJOGADOR.setForeground(Color.black);
        
        ImageIcon imgvazio = new ImageIcon("./src/imagens/vazio.png");
        
        jLabelJogador.setIcon(imgvazio);
        jLabelMaquina.setIcon(imgvazio);
        
        jButtonSetarPedra.setEnabled(false);
        jButtonSetarPapel.setEnabled(false);
        jButtonSetarTesoura.setEnabled(false);
    }//GEN-LAST:event_jButtonReiniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonIniciar;
    private javax.swing.JButton jButtonReiniciar;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JButton jButtonSetarPapel;
    private javax.swing.JButton jButtonSetarPedra;
    private javax.swing.JButton jButtonSetarTesoura;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelJOGADOR;
    private javax.swing.JLabel jLabelJogador;
    private javax.swing.JLabel jLabelMAQUINA;
    private javax.swing.JLabel jLabelMaquina;
    private javax.swing.JLabel jLabelPlacarJogador;
    private javax.swing.JLabel jLabelPlacarMaquina;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
